### ISSUE TITLE
Security hole in portal application

### ISSUE THREAD

**Issue by tarmo-profi** [i4Trust/pdc-portal#1]
# Security hole found in portal application.

If user has an authenticated session, the portal application is accessible with incognito mode or simply with another computer and is using same session with user.

## Reproduce

1. Login into application
2. Open new window in Incognito mode or ask someone to go /portal path
3. Access to application is granted and stranger can request entities

## Why this is happening?

Access token is handled & stored in backend, this means backend uses the same access token for every session.

## How to fix

We fixed this issue by getting the access token from browser instead of backend server.
The access token is handled in backend but it is being put into user's browser and access token is fetched from user's browser & used in functions which needs it.

Best Regards,
Tarmo

**Comment by dwendland** [comment]
Thank you for your finding!

Please note, that this is just a very simple demo application to showcase the necessary flows in an i4Trust data space. Main goal was to provide a code example of how to implement a simple application which retrieves an access token and interacts with a data service with the H2M flow. There were no security aspects considered, because this demo application is not meant to be used in any kind of production environment, but rather only for demonstrations of the very specific reference example use case.

Nevertheless, we would be glad if you want to provide your fix as PR in order to improve this demo application.
